language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  target-branch: master
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: daydayup
